# Generated by Django 4.2 on 2026-03-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="CRM Row ID (e.g., 251044)",
                        unique=True,
                    ),
                ),
                (
                    "board_id",
                    models.IntegerField(
                        db_index=True, default=70, help_text="CRM Board ID"
                    ),
                ),
                (
                    "group_id",
                    models.IntegerField(
                        blank=True, help_text="CRM Group ID", null=True
                    ),
                ),
                ("group_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client",
                    models.CharField(
                        blank=True,
                        help_text="Client/Borrower name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone_number_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "phone_number_formatted",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "phone_number_country",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("phone_number_valid", models.BooleanField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Failed payment amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Account balance",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Raw reason from CRM",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Action field (opt_0, 3rd NSF, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "wave",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Escalation wave (1-4)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        blank=True,
                        help_text="Assigned agent",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        help_text="Language preference",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date field from CRM", null=True
                    ),
                ),
                ("cell", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ref",
                    models.TextField(
                        blank=True, help_text="Reference field (JSON)", null=True
                    ),
                ),
                ("time_zone", models.CharField(blank=True, max_length=100, null=True)),
                ("work", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "comment",
                    models.TextField(blank=True, help_text="CRM comments", null=True),
                ),
                (
                    "email_metric_sent_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "email_metric_opened_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("email_metric_last_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "email_metric_last_opened",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_updated_start",
                    models.DateTimeField(
                        blank=True, help_text="CRM Last Updated start", null=True
                    ),
                ),
                (
                    "last_updated_end",
                    models.DateTimeField(
                        blank=True, help_text="CRM Last Updated end", null=True
                    ),
                ),
                ("world_clock", models.TextField(blank=True, null=True)),
                (
                    "raw_columns_json",
                    models.JSONField(
                        blank=True, help_text="Complete raw columns data", null=True
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, help_text="Last sync from CRM"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CRM Data",
                "verbose_name_plural": "CRM Data",
                "db_table": "crm_data",
                "ordering": ["-row_id"],
            },
        ),
        migrations.RenameIndex(
            model_name="collectioncase",
            new_name="collections_status_8b67e6_idx",
            old_name="collections_status_99f4ea_idx",
        ),
        migrations.RenameIndex(
            model_name="collectioncase",
            new_name="collections_automat_8d6c38_idx",
            old_name="collections_automat_4ec01d_idx",
        ),
        migrations.RenameIndex(
            model_name="collectioncase",
            new_name="collections_borrowe_20dbf2_idx",
            old_name="collections_borrower_30ef76_idx",
        ),
        migrations.RenameIndex(
            model_name="collectioncase",
            new_name="collections_next_fo_2c8d48_idx",
            old_name="collections_next_fo_667f30_idx",
        ),
        migrations.RenameIndex(
            model_name="interactionledger",
            new_name="collections_collect_adfb8b_idx",
            old_name="collections_collecti_46f693_idx",
        ),
        migrations.RenameIndex(
            model_name="interactionledger",
            new_name="collections_channel_e52c07_idx",
            old_name="collections_channel_f0f55d_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentcommitment",
            new_name="collections_collect_859830_idx",
            old_name="collections_collecti_7e6f9f_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentcommitment",
            new_name="collections_status_f34c82_idx",
            old_name="collections_status_9f0638_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionledger",
            new_name="collections_collect_9ed5ab_idx",
            old_name="collections_collecti_542a89_idx",
        ),
        migrations.AddIndex(
            model_name="crmdata",
            index=models.Index(fields=["row_id"], name="crm_data_row_id_e3b994_idx"),
        ),
        migrations.AddIndex(
            model_name="crmdata",
            index=models.Index(
                fields=["board_id", "group_id"], name="crm_data_board_i_106f29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmdata",
            index=models.Index(fields=["client"], name="crm_data_client_d12a87_idx"),
        ),
        migrations.AddIndex(
            model_name="crmdata",
            index=models.Index(
                fields=["phone_number_raw"], name="crm_data_phone_n_a7f1f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmdata",
            index=models.Index(fields=["wave"], name="crm_data_wave_a301f6_idx"),
        ),
        migrations.AddIndex(
            model_name="crmdata",
            index=models.Index(fields=["reason"], name="crm_data_reason_001bf1_idx"),
        ),
        migrations.AddIndex(
            model_name="crmdata",
            index=models.Index(
                fields=["created_at"], name="crm_data_created_faf3da_idx"
            ),
        ),
    ]
