# Generated by Django 4.2 on 2026-03-31 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0002_crmdata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.IntegerField(db_index=True, help_text="CRM Row ID")),
                (
                    "borrower",
                    models.CharField(
                        help_text="Borrower name (cleaned)", max_length=255
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Normalized phone (E.164 format)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Validated email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Failed payment amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "amount_plus_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount + $50 NSF fee",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Account balance",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Normalized reason code (NSF_EFT, STOP_PMT, ACCOUNT_FROZEN, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "wave",
                    models.IntegerField(
                        db_index=True, default=1, help_text="Escalation wave (1-4)"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True, help_text="Is this record valid for processing?"
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True, help_text="Any validation errors", null=True
                    ),
                ),
                (
                    "message_generated",
                    models.BooleanField(
                        default=False, help_text="Has a message been generated?"
                    ),
                ),
                (
                    "message_sent",
                    models.BooleanField(
                        default=False, help_text="Has the message been sent?"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, help_text="When was last message sent", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crm_data",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to raw CRM data",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_records",
                        to="collections.crmdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Data",
                "verbose_name_plural": "Ingestion Data",
                "db_table": "ingestion_data",
                "ordering": ["-row_id"],
            },
        ),
        migrations.CreateModel(
            name="MessagesOutbound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.IntegerField(db_index=True, help_text="CRM Row ID")),
                (
                    "borrower_name",
                    models.CharField(
                        help_text="Borrower name at send time", max_length=255
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone sent to", max_length=50, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email sent to", max_length=254, null=True
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")],
                        default="sms",
                        max_length=10,
                    ),
                ),
                (
                    "wave",
                    models.IntegerField(default=1, help_text="Wave at send time (1-4)"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_due",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "message_content",
                    models.TextField(help_text="Full message text sent"),
                ),
                (
                    "prompt_used",
                    models.TextField(
                        blank=True, help_text="Prompt sent to Gemini", null=True
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="gemini-2.5-flash",
                        help_text="AI model used",
                        max_length=50,
                    ),
                ),
                (
                    "generation_latency_ms",
                    models.IntegerField(
                        blank=True, help_text="AI response time in ms", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="heymarket, twilio, etc.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="External message ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, help_text="Full API response", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crm_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_messages",
                        to="collections.crmdata",
                    ),
                ),
                (
                    "ingestion_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_messages",
                        to="collections.ingestiondata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound Message",
                "verbose_name_plural": "Outbound Messages",
                "db_table": "messages_outbound",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessagesInbound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="CRM Row ID if identifiable",
                        null=True,
                    ),
                ),
                (
                    "from_phone",
                    models.CharField(
                        db_index=True,
                        help_text="Phone message came from",
                        max_length=50,
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email message came from",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "borrower_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")],
                        default="sms",
                        max_length=10,
                    ),
                ),
                (
                    "message_content",
                    models.TextField(help_text="Full message text received"),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="heymarket, twilio, etc.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "webhook_payload",
                    models.JSONField(
                        blank=True, help_text="Raw webhook data", null=True
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("will_pay", "Will Pay"),
                            ("request_delay", "Request Delay"),
                            ("dispute", "Dispute"),
                            ("cant_pay", "Cannot Pay"),
                            ("question", "Question"),
                            ("stop", "Stop/Opt-out"),
                            ("unclear", "Unclear"),
                            ("none", "No Intent"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "intent_confidence",
                    models.FloatField(
                        blank=True, help_text="AI confidence score 0-1", null=True
                    ),
                ),
                (
                    "intent_analysis",
                    models.JSONField(
                        blank=True, help_text="Full Gemini intent analysis", null=True
                    ),
                ),
                (
                    "commitment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("commitment_date", models.DateField(blank=True, null=True)),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="Has this been processed by AI?"
                    ),
                ),
                (
                    "requires_human",
                    models.BooleanField(
                        default=False, help_text="Flagged for human review"
                    ),
                ),
                ("human_notes", models.TextField(blank=True, null=True)),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, help_text="When message was received"
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crm_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_messages",
                        to="collections.crmdata",
                    ),
                ),
                (
                    "ingestion_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_messages",
                        to="collections.ingestiondata",
                    ),
                ),
                (
                    "outbound_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="The message this is replying to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="collections.messagesoutbound",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inbound Message",
                "verbose_name_plural": "Inbound Messages",
                "db_table": "messages_inbound",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddIndex(
            model_name="messagesoutbound",
            index=models.Index(fields=["row_id"], name="messages_ou_row_id_067022_idx"),
        ),
        migrations.AddIndex(
            model_name="messagesoutbound",
            index=models.Index(fields=["phone"], name="messages_ou_phone_eafdd9_idx"),
        ),
        migrations.AddIndex(
            model_name="messagesoutbound",
            index=models.Index(fields=["status"], name="messages_ou_status_1356fc_idx"),
        ),
        migrations.AddIndex(
            model_name="messagesoutbound",
            index=models.Index(
                fields=["channel"], name="messages_ou_channel_11f2b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagesoutbound",
            index=models.Index(fields=["wave"], name="messages_ou_wave_df8e91_idx"),
        ),
        migrations.AddIndex(
            model_name="messagesoutbound",
            index=models.Index(
                fields=["provider_message_id"], name="messages_ou_provide_c65b97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagesoutbound",
            index=models.Index(
                fields=["sent_at"], name="messages_ou_sent_at_a295a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagesoutbound",
            index=models.Index(
                fields=["created_at"], name="messages_ou_created_bb745f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagesinbound",
            index=models.Index(fields=["row_id"], name="messages_in_row_id_a40886_idx"),
        ),
        migrations.AddIndex(
            model_name="messagesinbound",
            index=models.Index(
                fields=["from_phone"], name="messages_in_from_ph_099be3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagesinbound",
            index=models.Index(fields=["intent"], name="messages_in_intent_ac9aeb_idx"),
        ),
        migrations.AddIndex(
            model_name="messagesinbound",
            index=models.Index(
                fields=["is_processed"], name="messages_in_is_proc_cdf8e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagesinbound",
            index=models.Index(
                fields=["requires_human"], name="messages_in_require_d53bff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagesinbound",
            index=models.Index(
                fields=["received_at"], name="messages_in_receive_a62bbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagesinbound",
            index=models.Index(
                fields=["created_at"], name="messages_in_created_ecc2d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestiondata",
            index=models.Index(fields=["row_id"], name="ingestion_d_row_id_222feb_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestiondata",
            index=models.Index(
                fields=["borrower"], name="ingestion_d_borrowe_59df82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestiondata",
            index=models.Index(fields=["phone"], name="ingestion_d_phone_567dd7_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestiondata",
            index=models.Index(
                fields=["reason_code"], name="ingestion_d_reason__b49508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestiondata",
            index=models.Index(fields=["wave"], name="ingestion_d_wave_39d2b6_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestiondata",
            index=models.Index(
                fields=["is_valid"], name="ingestion_d_is_vali_ab04bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestiondata",
            index=models.Index(
                fields=["message_sent"], name="ingestion_d_message_8e0111_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestiondata",
            index=models.Index(
                fields=["created_at"], name="ingestion_d_created_1098b2_idx"
            ),
        ),
    ]
