# Generated by Django 4.2 on 2026-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0003_ingestiondata_messagesoutbound_messagesinbound_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestiondata",
            name="row_id",
            field=models.IntegerField(
                db_index=True, help_text="CRM Row ID", unique=True
            ),
        ),
    ]
