"""MessagesOutbound Model - Gemini messages sent to borrowers"""

from django.db import models


class MessagesOutbound(models.Model):
    """
    Stores all outbound messages generated by Gemini and sent to borrowers.
    Tracks message content, delivery status, and API responses.
    """
    
    class Channel(models.TextChoices):
        SMS = 'sms', 'SMS'
        EMAIL = 'email', 'Email'
    
    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        SENT = 'sent', 'Sent'
        DELIVERED = 'delivered', 'Delivered'
        FAILED = 'failed', 'Failed'
    
    # Links to other tables
    crm_data = models.ForeignKey(
        'collections.CRMData',
        on_delete=models.SET_NULL,
        related_name='outbound_messages',
        null=True,
        blank=True
    )
    ingestion_data = models.ForeignKey(
        'collections.IngestionData',
        on_delete=models.SET_NULL,
        related_name='outbound_messages',
        null=True,
        blank=True
    )
    
    # Row reference
    row_id = models.IntegerField(db_index=True, help_text="CRM Row ID")
    
    # Recipient info
    borrower_name = models.CharField(max_length=255, help_text="Borrower name at send time")
    phone = models.CharField(max_length=50, null=True, blank=True, help_text="Phone sent to")
    email = models.EmailField(null=True, blank=True, help_text="Email sent to")
    channel = models.CharField(max_length=10, choices=Channel.choices, default=Channel.SMS)
    
    # Collection context at send time
    wave = models.IntegerField(default=1, help_text="Wave at send time (1-4)")
    amount = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    total_due = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    reason = models.CharField(max_length=255, null=True, blank=True)
    
    # Message content
    message_content = models.TextField(help_text="Full message text sent")
    
    # AI generation details
    prompt_used = models.TextField(null=True, blank=True, help_text="Prompt sent to Gemini")
    model = models.CharField(max_length=50, default='gemini-2.5-flash', help_text="AI model used")
    generation_latency_ms = models.IntegerField(null=True, blank=True, help_text="AI response time in ms")
    
    # Delivery details
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING, db_index=True)
    provider = models.CharField(max_length=50, null=True, blank=True, help_text="heymarket, twilio, etc.")
    provider_message_id = models.CharField(max_length=100, null=True, blank=True, help_text="External message ID")
    provider_status = models.CharField(max_length=50, null=True, blank=True)
    provider_response = models.JSONField(null=True, blank=True, help_text="Full API response")
    
    # Error tracking
    error_message = models.TextField(null=True, blank=True)
    retry_count = models.IntegerField(default=0)
    
    # Timestamps
    sent_at = models.DateTimeField(null=True, blank=True, db_index=True)
    delivered_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'messages_outbound'
        ordering = ['-created_at']
        verbose_name = 'Outbound Message'
        verbose_name_plural = 'Outbound Messages'
        indexes = [
            models.Index(fields=['row_id']),
            models.Index(fields=['phone']),
            models.Index(fields=['status']),
            models.Index(fields=['channel']),
            models.Index(fields=['wave']),
            models.Index(fields=['provider_message_id']),
            models.Index(fields=['sent_at']),
            models.Index(fields=['created_at']),
        ]
    
    def __str__(self):
        return f"Outbound {self.id} - Row {self.row_id} - {self.status}"
    
    def mark_sent(self, provider_response=None):
        """Mark message as sent."""
        from django.utils import timezone
        self.status = self.Status.SENT
        self.sent_at = timezone.now()
        if provider_response:
            self.provider_response = provider_response
            self.provider_message_id = provider_response.get('sms_log', {}).get('message_id') or \
                                       provider_response.get('message_id')
            self.provider_status = provider_response.get('status')
        self.save()
    
    def mark_failed(self, error_message):
        """Mark message as failed."""
        self.status = self.Status.FAILED
        self.error_message = error_message
        self.retry_count += 1
        self.save()
